### ISSUE TITLE
XCB rewrite

### ISSUE THREAD

**Issue by explosion-mental** [bakkeby/dusk#11]
Nothing serious, just some autism.. But there are some benefits in using `xcb` over the good old `Xlib`.
I've committed too much to my build to use another wm and I don't know other __dwm__ fork with that much modification than `dusk`.

This will be such tedious work, change all X functions to `xcb` ones.

Just wondering what's your opinion.

**Comment by explosion-mental** [comment]
Also, now that I think about it more deeply, this would require to change `libsl` as well (`drw.{c,h}`)..

**Comment by bakkeby** [comment]
I suppose that if you'd want to go down that route then you would probably better off building your window manager from the ground up rather than trying to substitute Xlib with XCB.

Or you just use i3 (or AwesomeWM). If you are serious about moving over to XCB with your existing build then this project, albeit old, would likely cover some of the groundwork needed:
https://github.com/nico2600/dwm_xcb

XCB is supposed to be smaller / leaner than Xlib. I mean it would be interesting to try some performance benchmarks between the two to see if makes any significant difference.

This is the only post on the topic that I could find, it is from 14 years ago:
https://dwm.suckless.narkive.com/ir2wclL8/xcb

**Comment by explosion-mental** [comment]
okay, in any way this isn't a scope of dusk. Thanks for the feedback, I will think about it.
