### ISSUE TITLE
hide un-used / empty WS in menu

### ISSUE THREAD

**Issue by deltahoch3** [bakkeby/dusk#25]
first of all, i use dusk for a few month now and really like it (used flexipatch before for +1y).

with the flexipatch version i was hiding the empty workspaces, is this also possible i dusk?

thanks in advanced and keep it up

**Comment by bakkeby** [comment]
I assume that you are referring to behaviour akin to the [hide vacant tags](https://dwm.suckless.org/patches/hide_vacant_tags/) patch for dwm?

There were a series of patches involving variations of tags like alternativetags and alttagsdecoration that made it cumbersome to maintain separately and independently, and at some point I ended up combining these ideas into a new patch called [tagicons](https://github.com/bakkeby/patches/wiki/tagicons) which was ultimately integrated into dwm-flexipatch.

dusk preserves these ideas, but rather than defining arrays of icons the icons are defined on a per workspace basis in the `wsrules` array.

Refer to the https://github.com/bakkeby/dusk/wiki/Workspace_Module#icons page.

At the end of the `wsrules` array you'll find the default, vacant and occupied workspace icons.

```c
   /* ...  def,   vac,  occ,  */
   {  ...  "1",   "",   "[1]", },
   {  ...  "2",   "",   "[2]", },
   {  ...  "3",   "",   "[3]", },
   {  ...  "4",   "",   "[4]", },
   {  ...  "5",   "",   "[5]", },
   {  ...  "6",   "",   "[6]", },
   {  ...  "7",   "",   "[7]", },
   {  ...  "8",   "",   "[8]", },
   {  ...  "9",   "",   "[9]", },
```

If the icon is an _empty string_ then the workspace will be hidden by default just like the hide vacant tags patch for dwm (and in the tagicons patch).

The _vacant_ icon is shown if the default icon is an empty string (hidden) and the workspace happens to be selected.

So to replicate the behaviour you just need to swap the two columns such that the default contain empty strings while the vacant ones contain the desired icons, e.g.

```c
   /* ...  def,   vac,  occ,  */
   {  ...  "",    "1",  "[1]", },
   {  ...  "",    "2",  "[2]", },
   {  ...  "",    "3",  "[3]", },
   {  ...  "",    "4",  "[4]", },
   {  ...  "",    "5",  "[5]", },
   {  ...  "",    "6",  "[6]", },
   {  ...  "",    "7",  "[7]", },
   {  ...  "",    "8",  "[8]", },
   {  ...  "",    "9",  "[9]", },
```

In this context it would probably make more sense to have a functionality toggle to enable or disable the feature. The reason why the default and vacant icons can be set independently here is because it may for example be desirable to always show workspaces 1 through 3, but hide the rest unless they are occupied.

**Comment by deltahoch3** [comment]
epic :) works perfectly as described 
![image](https://github.com/user-attachments/assets/304ab257-62a6-4a62-ae8a-33c091f4f243)
